// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfQ0F4MjcEP8v-G8qH2LZcbB8ty3IiUE8',
    appId: '1:848978343544:android:49f9fc63075f6e19771f8d',
    messagingSenderId: '848978343544',
    projectId: 'ninja-note-7c65b',
    databaseURL: 'https://ninja-note-7c65b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ninja-note-7c65b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLYaUMLJflnY81DElm_zkDY4XtkmhEbjc',
    appId: '1:848978343544:ios:8f1cbe6775667688771f8d',
    messagingSenderId: '848978343544',
    projectId: 'ninja-note-7c65b',
    databaseURL: 'https://ninja-note-7c65b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ninja-note-7c65b.appspot.com',
    iosBundleId: 'com.fanosbyte.ninjanote',
  );
}
